import urllib.request
import json
import dml
import prov.model
import datetime
import uuid
import sodapy
import geojson
from vincenty import vincenty
import scipy.stats

class BostonHotelCorrelation(dml.Algorithm):
    contributor = 'htw93_tscheung_wenjun'
    reads = ['htw93_tscheung_wenjun.BostonHotelCustomScore']
    writes = ['htw93_tscheung_wenjun.BostonHotelCorrelation']
    
    @staticmethod
    def execute(trial = False):
        '''Retrieve some data sets (not using the API here for the sake of simplicity).'''
        startTime = datetime.datetime.now()
        # Set up the database connection.
        client = dml.pymongo.MongoClient()
        repo = client.repo
        repo.authenticate('htw93_tscheung_wenjun', 'htw93_tscheung_wenjun')

        BostonHotelCustomScore = repo.htw93_tscheung_wenjun.BostonHotelCustomScore
        #BostonHotelRatingOriginal = repo.htw93_tscheung_wenjun.BostonHotel
        #HotelRaing = BostonHotelRatingOriginal.find()
        CustomScoreArr = BostonHotelCustomScore.find()

        OrginalScore = []
        CustomScore = []
        # Combine boston crime and boston schools.
        res = []
        
        
    
        for h in CustomScoreArr:
            print(h)
            OrginalScore.append([h['rate']])
            CustomScore.append([h['score']])

        print(OrginalScore)
        print(CustomScore)
        math = scipy.stats.pearsonr(OrginalScore, CustomScore)
        print("Correlation coefficient is " + str(math[0]))
        print("P-value is " + str(math[1]))        
        res.append({'coefficient':math[0][0], 'p_value':math[1][0]})

        repo.dropCollection("BostonHotelCorrelation")
        repo.createCollection("BostonHotelCorrelation")
        repo['htw93_tscheung_wenjun.BostonHotelCorrelation'].insert_many(res)
        print('Finished creating collection htw93_tscheung_wenjun.BostonHotelCorrelation')
        
        repo.logout()

        endTime = datetime.datetime.now()

        return {"start":startTime, "end":endTime}
    
    @staticmethod
    def provenance(doc = prov.model.ProvDocument(), startTime = None, endTime = None):
        '''
            Create the provenance document describing everything happening
            in this script. Each run of the script will generate a new
            document describing that invocation event.
            '''

        # Set up the database connection.
        client = dml.pymongo.MongoClient()
        repo = client.repo
        repo.authenticate('htw93_tscheung_wenjun', 'htw93_tscheung_wenjun')
        doc.add_namespace('alg', 'http://datamechanics.io/algorithm/') # The scripts are in <folder>#<filename> format.
        doc.add_namespace('dat', 'http://datamechanics.io/data/') # The data sets are in <user>#<collection> format.
        doc.add_namespace('ont', 'http://datamechanics.io/ontology#') # 'Extension', 'DataResource', 'DataSet', 'Retrieval', 'Query', or 'Computation'.
        doc.add_namespace('log', 'http://datamechanics.io/log/') # The event log.
        
        HotelCorrelation_script = doc.agent('alg:htw93_tscheung_wenjun#HotelCorrelation', {prov.model.PROV_TYPE:prov.model.PROV['SoftwareAgent'], 'ont:Extension':'py'})
        resource_BostonHotelCustomScore = doc.entity('dat:htw93_tscheung_wenjun#BostonHotelCustomScore', {'prov:label': 'BostonHotelCustomScore', prov.model.PROV_TYPE: 'ont:DataSet'})
        
        # define activity to represent invocaton of the script
        run_HotelCorrelation = doc.activity('log:uuid' + str(uuid.uuid4()), startTime, endTime)
        # associate the activity with the script
        doc.wasAssociatedWith(run_HotelCorrelation, HotelCorrelation_script)
        # indicate that an activity used the entity
        doc.usage(run_HotelCorrelation, resource_BostonHotelCustomScore, startTime, None, {prov.model.PROV_TYPE: 'ont:Computation'})

        # for the data obtained, indicate that the entity was attributed to what agent, was generated by which activity and was derived from what entity
        obtained_Correlation = doc.entity('dat:htw93_tscheung_wenjun#BostonHotelCorrelation', {prov.model.PROV_LABEL: 'BostonHotelCorrelation', prov.model.PROV_TYPE: 'ont:DataSet'})
        doc.wasAttributedTo(obtained_Correlation, HotelCorrelation_script)
        doc.wasGeneratedBy(obtained_Correlation, resource_BostonHotelCustomScore, endTime)
        doc.wasDerivedFrom(obtained_Correlation, resource_BostonHotelCustomScore, run_HotelCorrelation, run_HotelCorrelation, run_HotelCorrelation)
        

        repo.logout()
                  
        return doc

BostonHotelCorrelation.execute()
doc = BostonHotelCorrelation.provenance()
print(doc.get_provn())
print(json.dumps(json.loads(doc.serialize()), indent=4))

## eof
