import urllib.request
import json
import dml
import prov.model
import datetime
import uuid

class ppf(dml.Algorithm):
    contributor = 'raykatz_nedg_gaudiosi'
    reads = []
    writes = ['raykatz_nedg_gaudiosi.ppf']

    @staticmethod
    def execute(trial = False):
        '''Retrieve some data sets (not using the API here for the sake of simplicity).'''
        startTime = datetime.datetime.now()

        # Set up the database connection.
        client = dml.pymongo.MongoClient()
        repo = client.repo
        repo.authenticate('raykatz_nedg_gaudiosi','raykatz_nedg_gaudiosi')

        url = 'http://datamechanics.io/data/neighborhoodcrime.json'
        response = urllib.request.urlopen(url).read().decode("utf-8")
        result = json.loads(response)
        r=[]
        for i in range(600,len(result)):
            d={}
            if result[i]["FIELD2"]=='Charlestown':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='East Boston':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='Roxbury':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='Mattapan':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='South Boston':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='Dorchester':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='Brighton':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='West Roxbury':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='Jamaica Plain':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)
            d={}
            if result[i]["FIELD2"]=='Hyde Park':
                d["Region"]=result[i]["FIELD2"]
                h=196
                h+=1
                d["2012-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2012-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2013-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2014-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2015-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-08"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-09"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-10"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-11"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2016-12"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-01"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-02"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-03"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-04"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-05"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-06"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-07"]=result[i]["FIELD" + str(h)]
                h+=1
                d["2017-08"]=result[i]["FIELD" + str(h)]
                r.append(d)


                


        s = json.dumps(r, sort_keys=True, indent=2)
        repo.dropCollection("ppf")
        repo.createCollection("ppf")
        repo['raykatz_nedg_gaudiosi.ppf'].insert_many(r)
        repo['raykatz_nedg_gaudiosi.ppf'].metadata({'complete':True})
        print(repo['raykatz_nedg_gaudiosi.ppf'].metadata())


        repo.logout()

        endTime = datetime.datetime.now()

        return {"start":startTime, "end":endTime}
    
    @staticmethod
    def provenance(doc = prov.model.ProvDocument(), startTime = None, endTime = None):
        '''
            Create the provenance document describing everything happening
            in this script. Each run of the script will generate a new
            document describing that invocation event.
            '''

        # Set up the database connection.
        client = dml.pymongo.MongoClient()
        repo = client.repo
        repo.authenticate('raykatz_nedg_gaudiosi', 'raykatz_nedg_gaudiosi')
        doc.add_namespace('alg', 'http://datamechanics.io/algorithm/') # The scripts are in <folder>#<filename> format.
        doc.add_namespace('dat', 'http://datamechanics.io/data/') # The data sets are in <user>#<collection> format.
        doc.add_namespace('ont', 'http://datamechanics.io/ontology#') # 'Extension', 'DataResource', 'DataSet', 'Retrieval', 'Query', or 'Computation'.
        doc.add_namespace('log', 'http://datamechanics.io/log/') # The event log.

      
        this_script = doc.agent('alg:raykatz_nedg_gaudiosi#proj1', {prov.model.PROV_TYPE:prov.model.PROV['SoftwareAgent'], 'ont:Extension':'py'})
        resource = doc.entity('dat:raykatz_nedg_gaudiosi#neighborhoodcrime.json', {'prov:label':'Neighborhood Crime', prov.model.PROV_TYPE:'ont:DataResource', 'ont:Extension':'json'})

        get_ppf = doc.activity('log:uuid'+str(uuid.uuid4()), startTime, endTime)
        doc.wasAssociatedWith(get_ppf, this_script)
        doc.usage(get_ppf, resource, startTime, None,
                  {prov.model.PROV_TYPE:'ont:Retrieval',
                  'ont:Query':''
                  }
                  )


        ppf = doc.entity('dat:raykatz_nedg_gaudiosi#ppf', {prov.model.PROV_LABEL:'PPF', prov.model.PROV_TYPE:'ont:DataSet'})
        doc.wasAttributedTo(ppf, this_script)
        doc.wasGeneratedBy(ppf, get_ppf, endTime)
        doc.wasDerivedFrom(ppf, resource, get_ppf, get_ppf, get_ppf)

        repo.logout()
                  
        return doc
'''
ppf.execute()
doc = ppf.provenance()
print(doc.get_provn())
print(json.dumps(json.loads(doc.serialize()), indent=4))
'''
## eof
